In [2]:
import numpy as np
a = np.array([[1, 1, 1, 0],
              [3, 3, 3, 0],
              [4, 4, 4, 0],
              [5, 5, 5, 0]])

In [3]:
U, s, VT = np.linalg.svd(a, full_matrices=True)

In [4]:
U

array([[ -1.40028008e-01,   9.90147543e-01,   0.00000000e+00,
         -3.16421336e-17],
       [ -4.20084025e-01,  -5.94088526e-02,  -4.26401433e-02,
         -9.04534034e-01],
       [ -5.60112034e-01,  -7.92118034e-02,  -7.67522579e-01,
          3.01511345e-01],
       [ -7.00140042e-01,  -9.90147543e-02,   6.39602149e-01,
          3.01511345e-01]])

In [5]:
s

array([  1.23693169e+01,   2.88717587e-16,   1.63522227e-32,
         0.00000000e+00])

In [6]:
VT

array([[-0.57735027, -0.57735027, -0.57735027,  0.        ],
       [-0.81649658,  0.40824829,  0.40824829, -0.        ],
       [-0.        ,  0.70710678, -0.70710678, -0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])